customhost = "employeeprofile.ctfq1ueq6568.ap-southeast-1.rds.amazonaws.com"
customuser = "yinjiarui27"
custompass = "Injury1357924680!"
customdb = "employee"
custombucket = "registeremployee"
customregion = "ap-southeast-1"
